---
baseURL: "/manual/"
languageCode: "en-us"
title: "Fluxnova documentation"
theme: "fluxnova"

canonifyURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

blackfriday:
  plainIDAnchors: true

params:
#  canonicalBasePath: "https://docs.fluxnova.finos.org"
  version: "1.1"
#  versionAlias: "develop"
  forum:
    url: "https://github.com/finos/fluxnova-modeler/discussions"
    name: "Fluxnova Forum"
  # base URLs with optional version number in path using placeholder %s
  openApiBaseURL: "https://gaborherr.github.io/fluxnova-bpm-platform/openapi/%s"
  javadocsBaseURL: "https://gaborherr.github.io/fluxnova-bpm-platform/javadocs/%s"
  
  github:
    repositoryName: "finos/fluxnova-docs-manual"
    branch: "main"    

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
...
